### ISSUE TITLE
Fuck You

### ISSUE THREAD

**Issue by PotatoeTrainYT** [InfernoPE/InfernoPE-Core#1]
Oi bitch i think you'll find this core is actually [@MegaGastPvP](http://github.com/MegaGastPvP)'s Core But You Took It For Yourself

**Comment by InfernoPE** [comment]
@PotatoeTrainYT I'm making a core with the stuff you have and what's in @MegaGastPvP Core. Don't get mad but what i'm trying to say is you guys got what you need for a Core. I will be doing my own coding to just don't get pissed off okay.

**Comment by InfernoPE** [comment]
@PotatoeTrainYT CastleRaid Took my core with your stuff plus more.
